export enum ACTIONS {
	CHANGE_ITEMS_QUANTITY = "itemsPerPage/CHANGE_QUANTITY",
	IMAGE_SELECTED = "images/IMAGE_SELECTED",
	IMAGES_LOADED = "images/IMAGES_LOADED",
	GET_IMAGES_LIST = "images/GET_IMAGES_LIST",
}
