export enum ACTIONS {
  CHANGE_PAGE_LIMIT = "itemsPerPage/CHANGE_PAGE_LIMIT",
  IMAGES_LOADED = "images/IMAGES_LOADED",
  GET_IMAGES_LIST = "images/GET_IMAGES_LIST",
  SELECT_IMAGE_LOADED = "details/SELECT_IMAGE_LOADED",
  GET_IMAGE_DETAILS = "details/GET_IMAGE_DETAILS",
  GET_NUMBER_PAGES = "pagination/GET_NUMBER_PAGES",
  SET_CURRENT_PAGE = "pagination/SET_CURRENT_PAGE",
  SET_SORT_ORDER = "sort/SET_SORT_ORDER",
  SET_QUERY = "search/SET_QUERY"
}
